### ISSUE TITLE
SSH and SCP not working on linux+freertos demo

### ISSUE THREAD

**Issue by simonevallifuoco** [bao-project/bao-demos#17]
Hi, I am running Bao with dual-guest linux+freertos configuration on Qemu; I am trying to use SCP to copy a file to the linux guest, but I am getting this output: 
<img width="298" alt="scp" src="https://user-images.githubusercontent.com/73176205/218341620-a434a0bf-789d-494d-922a-35738f1711ee.png">

When trying to connect via SSH this is what i get:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/73176205/218342188-46e7efca-6ca8-4ccb-b3ca-51d21ac46360.png">

Am I making some mistake? What should I do?

**Comment by josecm** [comment]
@simonevallifuoco In my current setup, I am not able to replicate the issue. I'll look into it and get back to you.

**Comment by simonevallifuoco** [comment]
Thank you @josecm.
This is what happens when I try to ping the linux guest
<img width="306" alt="image" src="https://user-images.githubusercontent.com/73176205/218497510-5fe7c33d-9381-4b58-bd2e-59fa9288ca0c.png">

Instead, this is what happens when I try to ping the host from the linux guest:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/73176205/218497790-08bd97bc-26c5-4442-9b3b-76e853293567.png">

**Comment by simonevallifuoco** [comment]
Ok, looks like it's working now. In /etc/network/interfaces file eth0 was missing. I added it and run ifup eth0 command

**Comment by josecm** [comment]
> Thank you @josecm. This is what happens when I try to ping the linux guest <img alt="image" width="306" src="https://user-images.githubusercontent.com/73176205/218497510-5fe7c33d-9381-4b58-bd2e-59fa9288ca0c.png">
> 
> Instead, this is what happens when I try to ping the host from the linux guest: <img alt="image" width="222" src="https://user-images.githubusercontent.com/73176205/218497790-08bd97bc-26c5-4442-9b3b-76e853293567.png">

I'm not sure if you can route ICMP through [QEMU's user networking](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29).

> Ok, looks like it's working now. In /etc/network/interfaces eth0 was missing. I added it and run ifup eth0 command

I'm not able to replicate this. But natively on my machine and on a fresh Ubuntu VM eth0 always comes up during boot. Please update this thread if you identify the reason why it is failing on your setup. I'll do the same if I'm able to replicate the issue (and hopefully solve it).
