### ISSUE TITLE
Faile to make clean

### ISSUE THREAD

**Issue by tupelo-shen** [bao-project/bao-demos#29]
it seems to be that the rule of clean target is incorrect in Makefile of top directory of bao-demos project. The code snip is as follows:

```
clean: guests_clean bao_clean platform_clean
    -rm -rf $(wrkdir)/imgs/$(PLAT)/$(DEMO)
```
If execute `make PLATFORM=xxxx DEMO=yyyy clean` command, the result is:

```
rm -rf /PATH-TO-PROJECT/bao-demos/wrkdir/imgs//linux+freertos
```
There is nothing between the subdirectory `/imgs/` and `linux+freertos`. So, I think of PLAT variable should be replaced with PLATFORM. Like as follows:

```
clean: guests_clean bao_clean platform_clean
    -rm -rf $(wrkdir)/imgs/$(PLATFORM)/$(DEMO)
```

**Comment by josecm** [comment]
thanks for catching this @tupelo-shen

Just fixed it in [03cd073](https://github.com/bao-project/bao-demos/commit/03cd073b47178f25723ab9b2a2f77c67fe66566d).  If possible, next time please just send us a PR with the proposed fix!
