### ISSUE TITLE
Linux+Zephyr for rpi4

### ISSUE THREAD

**Issue by clachan** [bao-project/bao-demos#34]
Hi,

I wonder what is the main issue of Linux+Zephyr for rpi4?

Thanks,
Clay

**Comment by sandro2pinto** [comment]
Hi,

There is no big issue (apart from the fact Zephyr do not officially suport RPI4 - but this is not a big deal).

It is more a question of allocating HR to write a device tree and a bit of integration (and prepare de demo).

Thanks
Sandro

**Comment by clachan** [comment]
Thanks, @sandro2pinto. We plan to investigate and see what we can do about this.

Thanks,
Clay

**Comment by sandro2pinto** [comment]
Very nice @clachan! Please keep us posted and if you find any roadblocker let us know.

Thanks
Sandro

**Comment by danielRep** [comment]
I'll reopen the issue if anything comes up @clachan .

**Comment by josecm** [comment]
This was the correct PR to solve @yanjiew1! Thanks again.
